name: catalog
description: A test catalog for JW UI.
publish_to: 'none'


version: 1.0.0

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  j1_lints:
    git:
      url: https://github.com/J1-Apps/j1_lints.git
      ref: v1.0.0
